# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /src
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20-alpine 
WORKDIR /src
COPY --from=builder /src ./
RUN npm install --production

# Expose the port the app runs on
EXPOSE 3000

# Start the app in production mode
CMD ["npm", "run", "start"]
